/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    maven(url = "https://binrepo.target.com/artifactory/maven-central")
}

configurations {
    all{
        resolutionStrategy{
            force(libs.google.guava)
        }
    }
}

dependencies {
    testImplementation(libs.com.google.truth.truth)
    testImplementation(libs.com.google.testing.compile.compile.testing)
    testImplementation(libs.bundles.junit)
    testImplementation(libs.com.google.jimfs.jimfs)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.org.eclipse.jdt.core.compiler.ecj)
}

group = "com.squareup"
version = "1.14.0-SNAPSHOT"
description = "JavaPoet"
//java.sourceCompatibility = JavaVersion.VERSION_1_8
//java.sourceCompatibility = JavaVersion.VERSION_1_11

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
